<?php


/**
 * [BEGIN_COT_EXT]
 * Code=block404
 * Name=block404
 * Category=misc-ext
 * Description=block404
 * Version=1.0.0
 * Date=2014-03-18
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 *  */
/*
 * [BEGIN_COT_EXT_CONFIG]
 * 404=01:string:::404 page
 * [END_COT_EXT_CONFIG]
*/
/**
 * plugin block404 for Cotonti Siena
 * 
 * @package block404
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>