<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=header.first
 * [END_COT_EXT]
 */
 
/**
 * plugin block404 for Cotonti Siena
 * 
 * @package block404
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

if ($_GET['e'] == 'page' && $_GET['al'] == 'al404')
{
	$env['status'] = '404 Not Found';
}