<?php

/**
 * [BEGIN_COT_EXT]
 * Hooks=tools
 * [END_COT_EXT]
 */
/**
 * plugin block404 for Cotonti Siena
 * 
 * @package block404
 * @version 1.5.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('block404', 'plug');

$db_block404 = !empty($db_block404) ? $db_block404 : $db_x.'block404';
require_once cot_incfile('forms');

if ($a == 'delete')
{
	cot_check_xg();
	$db->delete($db_block404, "block404_id=$id");
	cot_redirect(cot_url('admin', 'm=other&p=block404', '', true));
}
elseif ($a == 'update')
{
	$block404_from = cot_import('rfrom', 'P', 'ARR');
	$block404_date = cot_import('rdate', 'P', 'ARR');
	$block404_regex = (int)cot_import('rregex', 'P', 'ARR');	
	
	foreach($block404_from as $key => $val)
	{
		$db_ins = array();
		$db_ins['block404_from'] = cot_import($block404_from[$key], 'D', 'TXT');
		$db_ins['block404_date'] = (int)cot_import_date($block404_date[$key], true, false, 'D');
		$db_ins['block404_regex'] = (int)cot_import($block404_regex[$key], 'D', 'BOL');
		$db->update($db_block404, $db_ins, "block404_id=$id");
	}
	cot_redirect(cot_url('admin', 'm=other&p=block404', '', true));
}
elseif ($a == 'add')
{
	$db_ins['block404_from'] = cot_import('rfrom', 'P', 'TXT');
	$db_ins['block404_date'] = (int)cot_import_date('rdate');
	$db_ins['block404_regex'] = (int)cot_import('rregex', 'P', 'BOL');
	if(!empty($db_ins['block404_from']) && !empty($db_ins['block404_to']))
	{
		$db->insert($db_block404, $db_ins);
	}
	cot_redirect(cot_url('admin', 'm=other&p=block404', '', true));
}

$t = new XTemplate(cot_tplfile('block404.tools', 'plug'));

$sql = $db->query("SELECT * FROM $db_block404 WHERE 1 ORDER BY block404_date DESC");
$ii = 0;
foreach ($sql->fetchAll() as $row)
{
	$ii++;
	$t->assign(array(
		'ADMIN_BLOCK404_DEL_URL' => cot_url('admin', 'm=other&p=block404&a=delete&id='.$row['block404_id'].'&'.cot_xg()),
		'ADMIN_BLOCK404_ITEM_ID' => $row['block404_id'],
		'ADMIN_BLOCK404_FROM' => cot_inputbox('text', 'rfrom['.$row['block404_id'].']', $row['block404_from'], 'style="width:98%;"'),
		'ADMIN_BLOCK404_DATE' => cot_selectbox_date((int)$row['block404_date'], 'short', 'rdate['.$row['block404_id'].']'),
		'ADMIN_BLOCK404_REGEX' => cot_checkbox($row['block404_regex'], 'rregex['.$row['block404_id'].']'),
		'ADMIN_BLOCK404_ODDEVEN' => cot_build_oddeven($ii)
	));

	$t->parse('MAIN.R301_ROW');
}
$t->assign('ADMIN_BLOCK404_UPDATE_URL', cot_url('admin', 'm=other&p=block404&a=update'));
if ($ii == 0)
{
	$t->parse('MAIN.R301_NOROW');
}
if ((int)$cfg['plugin']['block404']['defdates'] > 0)
{
	$utime = (int)$cfg['plugin']['block404']['defdates'] * 86400 + $sys['now'];
}
else
{
	$utime = 0;
}

$t->assign(array(
	'ADMIN_BLOCK404_ADD_URL' => cot_url('admin', 'm=other&p=block404&a=add'),
	'ADMIN_BLOCK404_FROM' => cot_inputbox('text', 'rfrom'),
	'ADMIN_BLOCK404_DATE' => cot_selectbox_date($utime, 'short', 'rdate'),
	'ADMIN_BLOCK404_REGEX' => cot_checkbox(false, 'rregex'),
));

$t->parse('MAIN');
if (COT_AJAX)
{
	$t->out('MAIN');
}
else
{
	$adminmain = $t->text('MAIN');
}
